### ISSUE TITLE
On-going maintenence after forking a pattern

### ISSUE THREAD

**Issue by RyanMillerC** [hybrid-cloud-patterns/docs#174]
I have a question I don't see an answer to anywhere in the docs. Happy to put an answer here into a PR!

**Question:** Let's say I've forked a pattern repo (multicluster-gitops for example) and deployed a hub cluster with a few managed clusters. A few months go by and the upstream project has had several changes. Am I expected to pull and merge those changes into my fork and redeploy?

**Comment by mbaldessari** [comment]
Hi @RyanMillerC,

Thanks for the question, let me try and give this question an initial tentative answer:

In general I think the answer is "Unless you need some new features from the upstream project, there is no need to upgrade your repo". There is also a bit of nuance in that answer, namely by default most (all?) patterns define some subscription based on certain channels without pinning a specific version, so your cluster is updating to a new operator versions as soon as they are released in that channel.

In general this is almost never a problem, but we have seen the occasional compatibility broken, which then either got fixed by a subsequent update or by a change in code. They are quite rare though, so it really depends.

Hope this covers your question somewhat?

**Comment by mbaldessari** [comment]
I am closing this one, let us know if there are any more questions/doubt about this
